// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeighBridge.Infrastructure.Persistence;

#nullable disable

namespace WeighBridge.Infrastructure.Migrations
{
    [DbContext(typeof(WeighBridgeDbContext))]
    [Migration("20260815104634_AddVehicleEntry")]
    partial class AddVehicleEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WeighBridge.Domain.Weighments.Weighment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NetWeightKg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NetWeightGrams");

                    b.Property<string>("PartyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlipNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransporterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("SlipNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("VehicleNumber");

                    b.ToTable("Weighments", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.Weighment", b =>
                {
                    b.OwnsOne("WeighBridge.Domain.Weighments.WeightCapture", "FirstWeight", b1 =>
                        {
                            b1.Property<long>("WeighmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("FirstWeightAtUtc");

                            b1.Property<long>("Kilograms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("FirstWeightGrams");

                            b1.Property<int>("Source")
                                .HasColumnType("INTEGER")
                                .HasColumnName("FirstWeightSource");

                            b1.HasKey("WeighmentId");

                            b1.ToTable("Weighments");

                            b1.WithOwner()
                                .HasForeignKey("WeighmentId");
                        });

                    b.OwnsOne("WeighBridge.Domain.Weighments.WeightCapture", "SecondWeight", b1 =>
                        {
                            b1.Property<long>("WeighmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("SecondWeightAtUtc");

                            b1.Property<long>("Kilograms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SecondWeightGrams");

                            b1.Property<int>("Source")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SecondWeightSource");

                            b1.HasKey("WeighmentId");

                            b1.ToTable("Weighments");

                            b1.WithOwner()
                                .HasForeignKey("WeighmentId");
                        });

                    b.Navigation("FirstWeight");

                    b.Navigation("SecondWeight");
                });
#pragma warning restore 612, 618
        }
    }
}
