// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeighBridge.Infrastructure.Persistence;

#nullable disable

namespace WeighBridge.Infrastructure.Migrations
{
    [DbContext(typeof(WeighBridgeDbContext))]
    partial class WeighBridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WeighBridge.Domain.Masters.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND IsActive = 1");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Masters.Party", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND IsActive = 1");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Masters.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TareWeightKg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TareWeightGrams");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long?>("VehicleTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("VehicleNumber")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND IsActive = 1");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Masters.VehicleType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0 AND IsActive = 1");

                    b.ToTable("VehicleTypes", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Messaging.SmsOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUsed")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SendingSinceUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("WeighmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("MessageKey")
                        .IsUnique();

                    b.HasIndex("SendingSinceUtc");

                    b.HasIndex("WeighmentId");

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.ToTable("SmsOutboxMessages", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Security.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.TicketReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConsumedByWeighmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlipNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TentativeVehicleNumber")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByWeighmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_TicketReservations_ConsumedByWeighmentId")
                        .HasFilter("[ConsumedByWeighmentId] IS NOT NULL");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_TicketReservations_CreatedAtUtc");

                    b.HasIndex("SlipNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_TicketReservations_SlipNumber")
                        .HasFilter("[SlipNumber] <> ''");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TicketReservations_Status");

                    b.ToTable("TicketReservations", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.Weighment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BagWeightKg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BagWeightGrams");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Charges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("ChargesPaise");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomField1")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomField2")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomField3")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomField4")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("GatePassNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NetWeightKg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NetWeightGrams");

                    b.Property<int?>("NumberOfBags")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecondCharges")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("SecondChargesPaise");

                    b.Property<string>("SlipNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransporterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<long?>("VehicleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleTypeName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PartyId");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("IX_Weighments_ReservationId")
                        .HasFilter("[ReservationId] IS NOT NULL");

                    b.HasIndex("SlipNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Weighments_SlipNumber")
                        .HasFilter("[SlipNumber] <> ''");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Weighments_VehicleNumber_Open")
                        .HasFilter("[Status] IN (0, 1) AND [IsDeleted] = 0");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Weighments", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.WeighmentImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Checksum")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("WeighmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("WeighmentId");

                    b.ToTable("WeighmentImages", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Infrastructure.Persistence.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Outcome");

                    b.HasIndex("Entity", "EntityId");

                    b.HasIndex("OccurredAtUtc", "OperatorName", "Action");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("WeighBridge.Domain.Masters.Vehicle", b =>
                {
                    b.HasOne("WeighBridge.Domain.Masters.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.TicketReservation", b =>
                {
                    b.HasOne("WeighBridge.Domain.Weighments.Weighment", null)
                        .WithMany()
                        .HasForeignKey("ConsumedByWeighmentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.Weighment", b =>
                {
                    b.HasOne("WeighBridge.Domain.Masters.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WeighBridge.Domain.Masters.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WeighBridge.Domain.Weighments.TicketReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WeighBridge.Domain.Masters.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WeighBridge.Domain.Masters.VehicleType", null)
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("WeighBridge.Domain.Weighments.WeightCapture", "FirstWeight", b1 =>
                        {
                            b1.Property<long>("WeighmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("FirstWeightAtUtc");

                            b1.Property<long>("Kilograms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("FirstWeightGrams");

                            b1.Property<int>("Source")
                                .HasColumnType("INTEGER")
                                .HasColumnName("FirstWeightSource");

                            b1.HasKey("WeighmentId");

                            b1.ToTable("Weighments");

                            b1.WithOwner()
                                .HasForeignKey("WeighmentId");
                        });

                    b.OwnsOne("WeighBridge.Domain.Weighments.WeightCapture", "SecondWeight", b1 =>
                        {
                            b1.Property<long>("WeighmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CapturedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("SecondWeightAtUtc");

                            b1.Property<long>("Kilograms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SecondWeightGrams");

                            b1.Property<int>("Source")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SecondWeightSource");

                            b1.HasKey("WeighmentId");

                            b1.ToTable("Weighments");

                            b1.WithOwner()
                                .HasForeignKey("WeighmentId");
                        });

                    b.Navigation("FirstWeight");

                    b.Navigation("SecondWeight");
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.WeighmentImage", b =>
                {
                    b.HasOne("WeighBridge.Domain.Weighments.Weighment", null)
                        .WithMany("Images")
                        .HasForeignKey("WeighmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeighBridge.Domain.Weighments.Weighment", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
