using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using WeighBridge.Core.Abstractions;
using WeighBridge.Core.Configuration;
using WeighBridge.Domain.Enums;

namespace WeighBridge.Hardware.WeightIndicators;

/// <summary>
/// Deterministic in-memory simulator for the weight indicator.
/// </summary>
/// <remarks>
/// Every reading generated by this simulator explicitly carries <see cref="WeightSource.Simulator"/>
/// so tests and audit logs never mistake simulated data for hardware evidence.
/// </remarks>
public sealed class WeightIndicatorSimulator : IWeightIndicatorService, IWeightIndicatorSimulator, IDisposable
{
    private readonly WeightIndicatorOptions _options;
    private readonly ILogger<WeightIndicatorSimulator> _logger;

    private ConnectionState _state = ConnectionState.Disconnected;
    private WeightReading _currentReading;
    private decimal _targetWeightKg = 0m;
    private bool _isStable = true;
    private bool _jitterEnabled;
    private decimal _jitterAmplitudeKg = 20m;
    private int _tickCount;

    private CancellationTokenSource? _timerCancellation;
    private Task? _timerTask;
    private readonly object _lock = new();

    public WeightIndicatorSimulator(
        IOptions<HardwareOptions> options,
        ILogger<WeightIndicatorSimulator> logger)
    {
        _options = options.Value.WeightIndicator;
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _currentReading = new WeightReading(0m, _options.Unit, false, DateTime.UtcNow, WeightSource.Simulator, "SIM-INIT");
    }

    /// <inheritdoc />
    public ConnectionState State
    {
        get => _state;
        private set
        {
            if (_state == value)
            {
                return;
            }

            _state = value;
            StateChanged?.Invoke(this, value);
        }
    }

    /// <inheritdoc />
    public WeightReading CurrentReading
    {
        get
        {
            lock (_lock)
            {
                return _currentReading;
            }
        }
        private set
        {
            lock (_lock)
            {
                _currentReading = value;
            }

            ReadingReceived?.Invoke(this, value);
        }
    }

    /// <inheritdoc />
    public string Name => "Weight Indicator (Simulator)";

    /// <inheritdoc />
    public event EventHandler<WeightReading>? ReadingReceived;

    /// <inheritdoc />
    public event EventHandler<ConnectionState>? StateChanged;

    /// <inheritdoc />
    public event EventHandler<DiagnosticDataChunk>? RawTelemetryReceived;

    /// <inheritdoc />
    public event EventHandler<ScaleAutoDetectedEventArgs>? ScaleAutoDetected { add { } remove { } }

    /// <inheritdoc />
    public Task<bool> ConnectAsync(CancellationToken cancellationToken = default)
    {
        lock (_lock)
        {
            if (_timerCancellation is not null)
            {
                return Task.FromResult(true);
            }

            State = ConnectionState.Connecting;
            _logger.LogInformation("Starting weight indicator simulator stream ({Interval}ms cadence)", _options.PollIntervalMilliseconds);

            _timerCancellation = new CancellationTokenSource();
            var token = _timerCancellation.Token;

            State = ConnectionState.Connected;

            _timerTask = Task.Run(async () =>
            {
                var interval = TimeSpan.FromMilliseconds(Math.Max(50, _options.PollIntervalMilliseconds));
                while (!token.IsCancellationRequested)
                {
                    try
                    {
                        await Task.Delay(interval, token).ConfigureAwait(false);
                        PublishTick();
                    }
                    catch (OperationCanceledException)
                    {
                        break;
                    }
                    catch (Exception ex)
                    {
                        _logger.LogWarning(ex, "Unexpected error in simulator tick loop");
                    }
                }
            }, token);

            return Task.FromResult(true);
        }
    }

    /// <inheritdoc />
    public async Task DisconnectAsync()
    {
        CancellationTokenSource? cts;
        Task? task;

        lock (_lock)
        {
            cts = _timerCancellation;
            task = _timerTask;
            _timerCancellation = null;
            _timerTask = null;
            State = ConnectionState.Disconnected;
        }

        if (cts is not null)
        {
            cts.Cancel();
            if (task is not null)
            {
                try
                {
                    await task.ConfigureAwait(false);
                }
                catch (OperationCanceledException)
                {
                }
            }

            cts.Dispose();

            // Logged only when there was something to disconnect. Disposal is legally
            // idempotent and the container captures this instance once per descriptor it
            // is registered under, so an unconditional line here reported the simulator
            // disconnecting twice on every shutdown - and once even when it had never
            // connected at all.
            _logger.LogInformation("Weight indicator simulator disconnected");
        }
    }

    /// <inheritdoc />
    public Task<WeightReading> ReadAsync(CancellationToken cancellationToken = default)
    {
        lock (_lock)
        {
            return Task.FromResult(_currentReading);
        }
    }

    /// <inheritdoc />
    public void SetWeight(decimal weightKg, bool isStable)
    {
        lock (_lock)
        {
            _targetWeightKg = weightKg;
            _isStable = isStable;
        }

        PublishTick();
    }

    /// <inheritdoc />
    public void SimulateDisconnect()
    {
        State = ConnectionState.Disconnected;
        _logger.LogInformation("Simulated weight indicator hardware disconnect triggered");
    }

    /// <inheritdoc />
    public void SimulateReconnect()
    {
        State = ConnectionState.Connected;
        _logger.LogInformation("Simulated weight indicator hardware reconnect triggered");
    }

    /// <inheritdoc />
    public void SetJitter(bool enabled, decimal amplitudeKg = 20m)
    {
        lock (_lock)
        {
            _jitterEnabled = enabled;
            _jitterAmplitudeKg = amplitudeKg;
        }
    }

    private void PublishTick()
    {
        if (State != ConnectionState.Connected)
        {
            return;
        }

        decimal value;
        bool stable;
        string raw;

        lock (_lock)
        {
            // Allow out-of-process weight setting for desktop automation testing and simulations when explicitly activated
            if (string.Equals(Environment.GetEnvironmentVariable("WEIGHBRIDGE_AUTOMATION_ACTIVE"), "1", StringComparison.OrdinalIgnoreCase))
            {
                string simControlFile = Path.Combine(Path.GetTempPath(), "weighbridge_sim_weight.txt");
                if (File.Exists(simControlFile))
                {
                    try
                    {
                        string content = File.ReadAllText(simControlFile).Trim();
                        if (!string.IsNullOrWhiteSpace(content))
                        {
                            string[] parts = content.Split(',');
                            if (decimal.TryParse(parts[0], System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var parsedWeight))
                            {
                                _targetWeightKg = parsedWeight;
                                if (parts.Length > 1 && bool.TryParse(parts[1], out var parsedStable))
                                {
                                    _isStable = parsedStable;
                                }
                            }
                        }
                    }
                    catch { }
                }
            }

            _tickCount++;
            decimal jitter = 0m;
            if (_jitterEnabled)
            {
                // Alternating deterministic wave for testing
                jitter = (_tickCount % 2 == 0 ? 1 : -1) * _jitterAmplitudeKg;
            }

            value = _targetWeightKg + jitter;
            stable = _isStable && !_jitterEnabled;
            raw = $"SIM,{(stable ? "ST" : "US")},+{value:000000}{_options.Unit}";
        }

        CurrentReading = new WeightReading(value, _options.Unit, stable, DateTime.UtcNow, WeightSource.Simulator, raw);
        try
        {
            var simBytes = System.Text.Encoding.ASCII.GetBytes(raw + "\r\n");
            var chunk = new DiagnosticDataChunk(simBytes, simBytes.Length, true, true, true);
            RawTelemetryReceived?.Invoke(this, chunk);
        }
        catch { }
    }

    /// <inheritdoc />
    public Task<HealthResult> CheckAsync(CancellationToken cancellationToken = default)
    {
        return Task.FromResult(State switch
        {
            ConnectionState.Connected => HealthResult.Healthy($"Simulator active ({CurrentReading.Value:N0} kg, {(CurrentReading.IsStable ? "stable" : "unstable")})"),
            ConnectionState.Disabled => HealthResult.Disabled("Simulator disabled in configuration"),
            _ => HealthResult.Degraded("Simulator disconnected"),
        });
    }

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        await DisconnectAsync().ConfigureAwait(false);
    }

    /// <inheritdoc />
    public void Dispose()
    {
        DisposeAsync().AsTask().GetAwaiter().GetResult();
    }
}
