namespace WeighBridge.Domain.Enums;

/// <summary>
/// Where a recorded weight came from.
/// </summary>
/// <remarks>
/// Persisted with every weight because it changes what the number is worth. A reading taken
/// from the indicator is evidence; a figure typed by an operator is a claim. A dispute over
/// a slip months later turns on which of the two it was, so the distinction is stored rather
/// than inferred.
/// </remarks>
public enum WeightSource
{
    /// <summary>Read from the weight indicator over its serial connection.</summary>
    Indicator = 0,

    /// <summary>Typed by the operator, because no indicator reading was available.</summary>
    Manual = 1,

    /// <summary>Generated by the development or testing simulator.</summary>
    Simulator = 2,
}
